### ISSUE TITLE
All configuration variables should be consistent and have clear default values

### ISSUE THREAD

**Issue by fergonco** [geoladris/core#28]
Currently we have PORTAL_CONFIG_DIR, MINIFIEDJS and NFMS_CONFIG_CACHE but some are jvm properties, some environment variables and some both.

All should be both jvm property and environment variable, with priority to the jvm property and I suggest renaming to this:

GEOLADRIS_CONFIG_DIR
GEOLADRIS_CONFIG_CACHE
GEOLADRIS_MINIFIED

... always keeping backwards compatibility.

**Comment by victorzinho** [comment]
We should fix the MainJSServlet [doGet method](https://github.com/geoladris/core/blob/release-5.0.x/core/src/main/java/org/geoladris/servlet/MainJSServlet.java#L31) and [tests](https://github.com/geoladris/core/blob/release-5.0.x/core/src/test/java/org/geoladris/servlet/MainJSServletTest.java#L43) when the variables are properly managed.
